debug: false

server:
  port: 8071

# Les clients s'enregistrent via spring-boot-admin-starter-client
#spring.boot.admin.ui.public-url: http://localhost:8070 # url proxy          

#############################################################################

# TODO : creuser enregistrement zookeeper
# https://github.com/codecentric/spring-boot-admin/blob/master/spring-boot-admin-samples/spring-boot-admin-sample-zookeeper/src/main/resources/application.yml

      
# mode cluster avec hazelcast pour synchroniser plusieurs instances
# TODO : utile si utilisation des notification ou pour d'autres cas ?
#        les 2 instances peuvent être indépendantes, les clients s'enregistrent sur les 2
# https://codecentric.github.io/spring-boot-admin/2.2.1/#clustering-support
